#!/usr/bin/env bash

# RUN AS ROOT
if [ $EUID -ne 0 ]
then
  echo -e "\033[1;31mRun script as root\033[0m" >&2
  exit 1
fi

# DOWNLOAD LATEST VERSION FOLLOWING API REDIRECTS
curl -L \
  --progress-bar \
  --request GET \
  --url 'https://discord.com/api/download/canary?platform=linux&format=tar.gz' \
  --output discord.tar.gz

# CLEAR OLD INSTALLATION
rm -rf \
  /usr/share/discord-canary\
  /bin/discord \
  /bin/discord-canary \
  /usr/share/applications/discord-canary.desktop

# INSTALL
tar -xf discord.tar.gz

cp -r DiscordCanary /usr/share/discord-canary

ln -s /usr/share/discord-canary/DiscordCanary /bin/discord
ln -s /usr/share/discord-canary/DiscordCanary /bin/discord-canary
ln -s /usr/share/discord-canary/discord-canary.desktop /usr/share/applications/discord-canary.desktop

# CLEANUP
rm -rf DiscordCanary discord.tar.gz
