#!/usr/bin/env bash
set -euo pipefail
# NOTE: add x to print commands
# readmore @ https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

# v4l2loopback is running
if [[ `lsmod | grep -q v4l2loopback_dc` -ne 0 ]]
then
  echo -e "\033[1;31mv4l2loopback daemon not found, check linux-headers\033[0m" >&2
  sys_version=`uname -r | cut -d'.' -f1,2 | sed 's/\.//g'`
  echo -e "Use command below and try again\n\tyay -S linux${sys_version}-headers gcc make usbmuxd v4l2loopback-dkms"
  echo -e "Might need to reboot after if\n\t`uname -r`\nis NOT your expected kernel version"
  exit 1
fi

# RUN AS ROOT
if [ $EUID -ne 0 ]
then
  echo -e "\033[1;31mRun script as root\033[0m" >&2
  exit 1
fi

# Uninstall previous version
/opt/droidcam-uninstall || echo "No uninstall script found"

# DOWNLOAD VERSION 1.8.2
# follow api redirects
curl -L \
  --progress-bar \
  --request GET \
  --url 'https://files.dev47apps.net/linux/droidcam_1.8.2.zip' \
  --output /tmp/droidcam_latest.zip

unzip -o /tmp/droidcam_latest.zip -d /tmp/droidcam

cd /tmp/droidcam && ./install-client

cd /tmp/droidcam && ./install-video

# how avoid conflict with OBS virtual camera?
# readmore @ https://github.com/obsproject/obs-studio/issues/3929#issuecomment-1118331263
